import type { PathShape, Horizon } from "./paths";
import type { RegimeId } from "./regimes";
import { baselineState, VAR_BY_ID, type VarState } from "./vars";

// The pre-built library. Every entry sets ABSOLUTE variable values, not deltas,
// so a preset is a complete statement of a world rather than an instruction
// that composes differently depending on what was on screen before it.
//
// Presets set several variables at once ON PURPOSE. A 100bp hike that leaves
// growth, the dollar and financial conditions at baseline is not a scenario, it
// is a partial derivative — and the model already gives that in the sensitivity
// tab. The point of the library is internally coherent worlds.

export interface Preset {
  id: string;
  label: string;
  group: string;
  /** One line. The narrative tab carries the argument. */
  gist: string;
  set: Partial<VarState>;
  path: PathShape;
  horizon: Horizon;
  /** Only set where the preset intends a regime the triggers would not pick. */
  regime?: RegimeId;
}

export const PRESET_GROUPS = [
  "Policy",
  "Inflation",
  "Growth",
  "Credit & Liquidity",
  "External",
  "Curve",
] as const;

export const PRESETS: Preset[] = [
  // ---- Policy --------------------------------------------------------------
  {
    id: "fed_25",
    label: "Fed +25bp",
    group: "Policy",
    gist: "Single insurance hike, guidance unchanged",
    set: { fedFunds: 4.25, forwardGuidance: 0.25, realRate10y: 2.0 },
    path: "immediate",
    horizon: 3,
  },
  {
    id: "fed_50",
    label: "Fed +50bp",
    group: "Policy",
    gist: "Two hikes priced, front end leads",
    set: { fedFunds: 4.5, forwardGuidance: 0.5, realRate10y: 2.1, vix: 17 },
    path: "staged",
    horizon: 6,
  },
  {
    id: "fed_75",
    label: "Fed +75bp",
    group: "Policy",
    gist: "Restrictive turn with a growth cost",
    set: { fedFunds: 4.75, forwardGuidance: 1.0, realRate10y: 2.25, vix: 19, gdpGrowth: 1.4, fciComposite: 0.5 },
    path: "staged",
    horizon: 6,
  },
  {
    id: "fed_100",
    label: "Fed +100bp",
    group: "Policy",
    gist: "Full hiking cycle: curve flattens, conditions tighten, growth slows",
    set: {
      fedFunds: 5.0,
      forwardGuidance: 1.5,
      realRate10y: 2.4,
      vix: 21,
      gdpGrowth: 1.0,
      fciComposite: 0.8,
      igSpread: 115,
      dxy: 106,
    },
    path: "scurve",
    horizon: 12,
  },
  {
    id: "fed_cut_100",
    label: "Fed −100bp",
    group: "Policy",
    gist: "Easing cycle into a soft patch, not a crisis",
    set: { fedFunds: 3.0, forwardGuidance: -1.25, realRate10y: 1.4, gdpGrowth: 1.5, unemployment: 4.6, dxy: 100 },
    path: "scurve",
    horizon: 12,
  },
  {
    id: "ecb_75",
    label: "ECB +75bp",
    group: "Policy",
    gist: "Euro-area tightening with no Fed response",
    set: { ecbDepo: 3.0, eurusd: 1.12 },
    path: "staged",
    horizon: 6,
  },
  {
    id: "boj_normalise",
    label: "BoJ Normalisation",
    group: "Policy",
    gist: "Yield curve control fully unwound; carry trade reverses",
    set: { bojPolicy: 1.75, usdjpy: 136, vix: 20 },
    path: "linear",
    horizon: 12,
  },
  {
    id: "boe_100",
    label: "BoE +100bp",
    group: "Policy",
    gist: "Sticky UK services inflation forces the Bank's hand",
    set: { boeBank: 4.75, gbpusd: 1.31 },
    path: "staged",
    horizon: 6,
  },
  {
    id: "qt_accel",
    label: "QT Acceleration",
    group: "Policy",
    gist: "Runoff doubles; term premium rebuilds without a policy-rate move",
    set: { qtPace: 90, fedBalanceSheet: 19, realRate10y: 2.3, fciComposite: 0.6 },
    path: "linear",
    horizon: 12,
  },

  // ---- Inflation -----------------------------------------------------------
  {
    id: "infl_sudden",
    label: "Inflation Shock: Sudden",
    group: "Inflation",
    gist: "Prints reaccelerate in one quarter; expectations follow",
    set: {
      cpiHeadline: 5.8,
      cpiCore: 5.0,
      pceCore: 4.6,
      be5y: 3.0,
      be10y: 2.8,
      wageGrowth: 5.2,
      fedFunds: 4.75,
      forwardGuidance: 1.25,
      realRate10y: 2.3,
      vix: 22,
    },
    path: "immediate",
    horizon: 6,
  },
  {
    id: "infl_gradual",
    label: "Inflation Shock: Gradual",
    group: "Inflation",
    gist: "Same terminal inflation, delivered over a year",
    set: {
      cpiHeadline: 5.8,
      cpiCore: 5.0,
      pceCore: 4.6,
      be5y: 3.0,
      be10y: 2.8,
      wageGrowth: 5.2,
      fedFunds: 4.75,
      forwardGuidance: 1.25,
      realRate10y: 2.3,
    },
    path: "linear",
    horizon: 12,
  },
  {
    id: "disinflation",
    label: "Disinflation Surprise",
    group: "Inflation",
    gist: "Core rolls over faster than the Fed's path assumed",
    set: {
      cpiHeadline: 1.7,
      cpiCore: 2.0,
      pceCore: 1.9,
      be5y: 2.05,
      be10y: 2.1,
      wageGrowth: 3.2,
      fedFunds: 3.25,
      forwardGuidance: -1.0,
      realRate10y: 1.5,
      fwdPE: 21.5,
    },
    path: "scurve",
    horizon: 12,
  },
  {
    id: "stagflation",
    label: "Stagflation",
    group: "Inflation",
    gist: "Inflation up, growth down, and duration does not hedge",
    set: {
      cpiHeadline: 6.2,
      cpiCore: 5.4,
      pceCore: 4.9,
      be5y: 3.2,
      be10y: 3.0,
      wageGrowth: 5.8,
      productivity: 0.2,
      gdpGrowth: 0.3,
      pmiMfg: 46,
      pmiSvcs: 49.5,
      unemployment: 4.9,
      earningsGrowth: -2,
      earningsRevisions: -18,
      fedFunds: 5.0,
      forwardGuidance: 1.0,
      realRate10y: 2.6,
      vix: 26,
      igSpread: 145,
      hyBBSpread: 340,
      energySupply: 8,
    },
    path: "scurve",
    horizon: 12,
  },

  // ---- Growth --------------------------------------------------------------
  {
    id: "soft_landing",
    label: "Soft Landing",
    group: "Growth",
    gist: "Inflation normalises without a labour-market break",
    set: {
      cpiHeadline: 2.3,
      cpiCore: 2.4,
      pceCore: 2.2,
      gdpGrowth: 1.8,
      unemployment: 4.4,
      pmiMfg: 51,
      pmiSvcs: 54,
      fedFunds: 3.5,
      forwardGuidance: -0.5,
      realRate10y: 1.6,
      vix: 14,
      earningsGrowth: 8,
    },
    path: "linear",
    horizon: 12,
  },
  {
    id: "goldilocks",
    label: "Goldilocks",
    group: "Growth",
    gist: "Productivity absorbs wage growth; multiples expand",
    set: {
      cpiCore: 2.2,
      cpiHeadline: 2.1,
      pceCore: 2.0,
      gdpGrowth: 2.9,
      productivity: 2.6,
      unemployment: 4.0,
      pmiMfg: 54,
      pmiSvcs: 57,
      earningsGrowth: 14,
      earningsRevisions: 12,
      vix: 12,
      igSpread: 82,
      hyBBSpread: 185,
    },
    path: "linear",
    horizon: 12,
  },
  {
    id: "recession_pmi",
    label: "Recession: Demand Collapse",
    group: "Growth",
    gist: "Orders and output roll first; labour follows late",
    set: {
      gdpGrowth: -1.8,
      pmiMfg: 42,
      pmiSvcs: 46,
      regionalFed: -22,
      unemployment: 5.0,
      earningsGrowth: -14,
      earningsRevisions: -35,
      cpiCore: 2.2,
      cpiHeadline: 1.6,
      fedFunds: 2.75,
      forwardGuidance: -1.75,
      realRate10y: 1.0,
      vix: 29,
      igSpread: 165,
      hyBBSpread: 420,
      hyBCCCSpread: 950,
      fciComposite: 1.1,
    },
    path: "scurve",
    horizon: 12,
  },
  {
    id: "recession_labour",
    label: "Recession: Labour Break",
    group: "Growth",
    gist: "Unemployment gaps higher; the consumer stops",
    set: {
      unemployment: 6.3,
      participation: 62.1,
      gdpGrowth: -2.4,
      pmiSvcs: 44,
      pmiMfg: 44,
      wageGrowth: 2.6,
      earningsGrowth: -20,
      earningsRevisions: -45,
      cpiCore: 2.0,
      cpiHeadline: 1.2,
      fedFunds: 2.0,
      forwardGuidance: -2.25,
      realRate10y: 0.6,
      vix: 33,
      igSpread: 190,
      hyBBSpread: 500,
      hyBCCCSpread: 1150,
      fciComposite: 1.4,
    },
    path: "scurve",
    horizon: 24,
  },

  // ---- Credit & liquidity --------------------------------------------------
  {
    id: "credit_crisis",
    label: "Credit Crisis",
    group: "Credit & Liquidity",
    gist: "Funding stress, not a growth forecast, sets prices",
    set: {
      vix: 44,
      igSpread: 260,
      hyBBSpread: 720,
      hyBCCCSpread: 1650,
      fciComposite: 2.6,
      emStress: 7.5,
      gdpGrowth: -1.0,
      unemployment: 5.1,
      earningsRevisions: -30,
      fedFunds: 3.0,
      forwardGuidance: -2.0,
      fedBalanceSheet: 25,
      qtPace: 0,
      dxy: 108,
    },
    path: "immediate",
    horizon: 6,
  },
  {
    id: "liquidity_squeeze",
    label: "Liquidity Squeeze",
    group: "Credit & Liquidity",
    gist: "Balance-sheet withdrawal with no credit event behind it",
    set: { qtPace: 130, fedBalanceSheet: 17, fciComposite: 1.5, vix: 27, igSpread: 150, realRate10y: 2.5, dxy: 108 },
    path: "linear",
    horizon: 12,
  },
  {
    id: "vol_shock",
    label: "Volatility Shock",
    group: "Credit & Liquidity",
    gist: "Positioning unwind; risk premium repricing with clean fundamentals",
    set: { vix: 38, fciComposite: 1.6, hyBCCCSpread: 880, igSpread: 140, usdjpy: 141 },
    path: "meanRevert",
    horizon: 6,
  },

  // ---- External ------------------------------------------------------------
  {
    id: "oil_spike",
    label: "Energy Supply Shock",
    group: "External",
    gist: "Supply withdrawn, not demand added; equities and oil move opposite ways",
    set: {
      energySupply: 28,
      cpiHeadline: 5.4,
      cpiCore: 3.6,
      be5y: 2.85,
      termsOfTrade: -6,
      gdpGrowth: 0.8,
      vix: 26,
      fedFunds: 4.5,
      forwardGuidance: 0.75,
    },
    path: "immediate",
    horizon: 6,
  },
  {
    id: "em_crisis",
    label: "EM Currency Crisis",
    group: "External",
    gist: "Dollar funding squeeze concentrated outside the G3",
    set: {
      emStress: 8.5,
      dxy: 112,
      usdmxn: 22.5,
      usdbrl: 6.8,
      usdcny: 7.55,
      vix: 30,
      hyBCCCSpread: 900,
      igSpread: 150,
      gdpGrowth: 1.2,
    },
    path: "immediate",
    horizon: 6,
  },
  {
    id: "dollar_debasement",
    label: "Dollar Debasement",
    group: "External",
    gist: "Fiscal path, not growth, drives the dollar and the long end",
    set: {
      deficitGdp: 9.5,
      debtGdp: 140,
      currentAccount: -5.2,
      dxy: 93,
      be10y: 2.9,
      realRate10y: 2.4,
      fedBalanceSheet: 26,
    },
    path: "linear",
    horizon: 24,
  },
  {
    id: "commodity_bull",
    label: "Commodity Super-Cycle: Bull",
    group: "External",
    gist: "Global capex cycle with a soft dollar",
    set: {
      gdpGrowth: 3.2,
      pmiMfg: 56,
      pmiSvcs: 56,
      usdcny: 6.85,
      dxy: 95,
      cpiHeadline: 3.6,
      cpiCore: 3.2,
      be5y: 2.7,
      termsOfTrade: 4,
      energySupply: 6,
    },
    path: "scurve",
    horizon: 24,
  },
  {
    id: "commodity_bear",
    label: "Commodity Super-Cycle: Bear",
    group: "External",
    gist: "Supply glut and a China demand air pocket",
    set: {
      energySupply: -14,
      usdcny: 7.6,
      emStress: 5.5,
      pmiMfg: 46,
      gdpGrowth: 1.2,
      cpiHeadline: 1.4,
      dxy: 107,
      termsOfTrade: 5,
    },
    path: "linear",
    horizon: 12,
  },

  // ---- Curve ---------------------------------------------------------------
  {
    id: "curve_invert",
    label: "Curve Inversion",
    group: "Curve",
    gist: "Front end held high while the long end prices the slowdown",
    set: { fedFunds: 5.0, forwardGuidance: 1.25, gdpGrowth: 0.6, pmiMfg: 46, be10y: 2.1, realRate10y: 1.7, cpiCore: 2.6 },
    path: "linear",
    horizon: 12,
  },
  {
    id: "bull_steepen",
    label: "Bull Steepening",
    group: "Curve",
    gist: "Cuts priced into the front end; long end anchored",
    set: { fedFunds: 2.75, forwardGuidance: -2.0, unemployment: 5.2, gdpGrowth: 0.4, cpiCore: 2.3, realRate10y: 1.3 },
    path: "scurve",
    horizon: 12,
  },
  {
    id: "bear_steepen",
    label: "Bear Steepening",
    group: "Curve",
    gist: "Term premium rebuilds on supply, not on growth",
    set: { deficitGdp: 9.0, debtGdp: 136, qtPace: 100, be10y: 2.85, realRate10y: 2.6, fedFunds: 4.0, currentAccount: -4.4 },
    path: "linear",
    horizon: 24,
  },
];

export const PRESET_BY_ID: Record<string, Preset> = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

/** A preset applied to a clean baseline. Presets never compose with each other. */
export function presetState(p: Preset): VarState {
  const s = baselineState();
  for (const [k, v] of Object.entries(p.set)) {
    if (VAR_BY_ID[k] && typeof v === "number") s[k] = v;
  }
  return s;
}
